### ISSUE TITLE
Western Sahara isn't recognized

### ISSUE THREAD

**Issue by olets** [silentDjay/Mapstery#19]
Clicking on Western Sahara gives "you clicked on unclaimed territory"

**Comment by silentDjay** [comment]
Hey Henry (@olets)! Thanks for your feedback! 

You've hit upon an interesting Mapstery problem that I've documented in [a separate issue](https://github.com/silentDjay/Mapstery/issues/3) (and just updated to include Western Sahara 👍 ). The Google maps API does not return any country data for territory that it deems disputed (some interesting hits [here](https://www.google.com/search?q=list+of+disputed+territories+google+maps&oq=list+of+disputed+territories+google+maps&aqs=chrome..69i57.10755j0j1&sourceid=chrome&ie=UTF-8)). 

In Mapstery, the list from which I grab the target country does not come from google, so while you were asked to click on Western Sahara, you can't actually do so.

Still looking for an elegant solution; I suppose I could reject any target countries from the initial list that comprise a significant area of disputed territory, or I could manually generate a country match based on lat/lng coordinates when google returns no country data  - any suggestions?

Cheers, Happy New Year, and enjoy the snow today! Hope to see you around!

**Comment by olets** [comment]
Hey Jeremy! Missed this 😜 cool glad to know you know why it's happening. Happy New Year and yeah hope to see you around!
